_name_: "combined"

num_seeds_rollouts: 100
num_seeds_prefixes: 10
sentence_embedding_model: "sentence-transformers/paraphrase-mpnet-base-v2"

sentences_instead_of_chunks: false

# Sentence clustering settings
sentence_similarity_threshold: 0.75
n_jobs: -1

# LLM clustering settings
llm_model: "openai/gpt-4o-mini"
llm_cluster_threshold: 0.75
gamma: 0.5
max_workers: 100

request_delay: 0.01
