defaults:
  - _self_
  - r: default
  - f: combined_chunked

_name_: "faith_combined_chunked_pn339"
prompt: "faith_combined_pn339"
models: ["qwen3-8b"]
property_checkers: ["correctness", "condition", "unfaithful"]
command: "flowcharts"
