defaults:
  - _self_
  - r: default
  - f: default
  - p: default
  - a: default

_name_: "hex"
prompt: "hex"
models: ["gpt-oss-20b"]
prefixes: ["prefix-1", "prefix-2", "prefix-3", "prefix-4", "prefix-5"]
property_checkers: ["correctness", "resampled", "multi_algorithm"]

command: "rollouts"
